name: SPT Release With Fika Builder

on:
  workflow_dispatch:  # trigger manually
    inputs:
      sptBuildTag:
        description: "The spt tag to build on"
        required: true
        type: string
      fikaBuildTag:
        description: "The fika server tag to build on"
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.check-existence.outputs.proceed }}
      repo_spt: ${{ steps.check-existence.outputs.repo_spt }}
      repo_fika_server: ${{ steps.check-existence.outputs.repo_fika_server }}
      repo_fika_plugin: ${{ steps.check-existence.outputs.repo_fika_plugin }}
      tag_spt: ${{ steps.check-existence.outputs.tag_spt }}
      tag_fika: ${{ steps.check-existence.outputs.tag_fika }}
      spt_version: ${{ steps.versions.outputs.spt_version }}
    steps:
      - name: Check Existence
        id: check-existence
        shell: bash
        env:
          EVENT_NAME: ${{ github.event_name }}
          SPT_SERVER_REPO: "https://github.com/sp-tarkov/server-csharp.git"
          FIKA_SERVER_REPO: "https://github.com/project-fika/Fika-Server-CSharp.git"
          FIKA_PLUGIN_REPO: "https://github.com/project-fika/Fika-Plugin.git"
          SPTBUILDTAG: ${{ github.event.inputs.sptBuildTag }}
          FIKABUILDTAG: ${{ github.event.inputs.fikaBuildTag }}
        run: |
          echo "Check existence"
          PROCEED="true"
          SPT_TAG=$SPTBUILDTAG
          FIKA_TAG=$FIKABUILDTAG

          declare -A REPOS_TAG

          REPOS_TAG[$SPT_SERVER_REPO]="$SPTBUILDTAG"
          REPOS_TAG[$FIKA_SERVER_REPO]="$FIKABUILDTAG"
          
          for REPO in "${!REPOS_TAG[@]}"; do
            echo "Checking for tag $TAG in $REPO..."
            TAG=${REPOS_TAG[$REPO]}
            if ! git ls-remote --tags $REPO $TAG | grep -q $TAG; then
              echo "Tag $TAG not found in $REPO"
              PROCEED="false"
              break
            fi
          done
          echo "proceed=$PROCEED" >> $GITHUB_OUTPUT

          if [ "$PROCEED" = "true" ]; then
            echo "repo_spt=$SPT_SERVER_REPO" >> $GITHUB_OUTPUT
            echo "repo_fika_server=$FIKA_SERVER_REPO" >> $GITHUB_OUTPUT
            echo "repo_fika_plugin=$FIKA_PLUGIN_REPO" >> $GITHUB_OUTPUT
            echo "tag_spt=$SPTBUILDTAG" >> $GITHUB_OUTPUT
            echo "tag_fika=$FIKABUILDTAG" >> $GITHUB_OUTPUT
          fi
          echo "Matches found. Proceeding with build."
      
      - name: Tag Not Found
        if: steps.check-existence.outputs.proceed == 'false'
        run: |
          echo "Required branch/tag not found in one or more repositories, halting workflow."
          exit 1

      - name: Extract Versions
        id: versions
        shell: bash
        run: |
          # 初始化工作区
          rm -rf /workspace/build/spt-server
          sudo mkdir -p /workspace/build && sudo chown -R `whoami`:`groups | awk '{print $1}'` /workspace
          
          # 初始化仓库
          git init /workspace/build/spt-server
          cd /workspace/build/spt-server
          git remote add origin ${{ steps.check-existence.outputs.repo_spt }}

          # 配置仓库, 启用稀疏检出, 避免为了获取内部版本号而需要下载整个仓库
          git config core.sparseCheckout true
          echo "Build.props" >> .git/info/sparse-checkout

          git fetch --depth=1 origin "${{ steps.check-existence.outputs.tag_spt }}"
          git checkout FETCH_HEAD

          # 获取 SPT 内部版本
          SPT_VERSION=$(sed -n 's/.*<SptVersion[^>]*>\([0-9]\+\.[0-9]\+\.[0-9]\+\)<\/SptVersion>.*/\1/p' Build.props)

          echo "spt_version=$SPT_VERSION" >> $GITHUB_OUTPUT
          echo "SPT version is $SPT_VERSION"
      
  build-spt:
    needs: prepare
    if: needs.prepare.outputs.proceed == 'true'
    runs-on: ubuntu-latest
    container:
      image: refringe/spt-build-dotnet:2.1.0
    outputs:
      spt_server_version: ${{ steps.clone-spt-server.outputs.spt_version }}
      spt_server_commit: ${{ steps.commit-hash.outputs.sp }}
    steps:
      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
          apt-get install git-lfs

      - name: Clone SPT Server
        id: clone-spt-server
        shell: bash
        run: |
          serverPath="/workspace/build/spt-server"

          # Delete old remnants of the last build.
          if [ -d "$serverPath" ]; then
              rm -rf "$serverPath"
          fi
          mkdir -p $serverPath
          chown -R `whoami`:`groups | awk '{print $1}'` $serverPath

          TARGET="${{ needs.prepare.outputs.tag_spt }}"

          echo "Cloning target: $TARGET"
          git clone ${{ needs.prepare.outputs.repo_spt }} --branch "$TARGET" --depth 1 "$serverPath"

          # Pull LFS files.
          cd "$serverPath" || exit
          git lfs install --local
          git lfs pull

          echo "spt_version=${{ needs.prepare.outputs.spt_version }}" >> $GITHUB_OUTPUT

      - name: Output Commit Hash
        id: commit-hash
        shell: bash
        run: echo "spt_server_commit=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        working-directory: /workspace/build/spt-server

      - name: Pull LFS Files
        run: |
          git lfs pull 
        working-directory: /workspace/build/spt-server
      
      - name: Build Spt Server
        shell: bash
        run: |
          sed -i 's@127.0.0.1@0.0.0.0@g' ./Libraries/SPTarkov.Server.Assets/SPT_Data/configs/http.json
          dotnet publish -f net9.0 ./SPTarkov.Server/SPTarkov.Server.csproj \
          -c Release \
          -r linux-x64 \
          --self-contained false \
          -p:SptBuildType=RELEASE \
          -p:SptVersion=${{ needs.prepare.outputs.spt_version }} \
          -p:SptBuildTime=$( date +%Y%m%d )
          -p:SptBuildCommit=${{ needs.prepare.outputs.spt_server_commit }}
          -p:IsPublish=true
          
          mkdir -p /workspace/build/spt-server/project/target
          tar -cf - -C ./SPTarkov.Server/bin/Release/net9.0/linux-x64/publish --exclude='*.pdb' . | tar -xf - -C /workspace/build/spt-server/project/target
        working-directory: /workspace/build/spt-server/project

      - name: Upload SPT Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spt-server-artifact
          path: /workspace/build/spt-server/project/target
          retention-days: 1
          if-no-files-found: error
    
  build-fika:
    needs: prepare
    if: needs.prepare.outputs.proceed == 'true'
    runs-on: ubuntu-latest
    outputs:
      fika_server_version: ${{ steps.clone-fika-server-and-plugin.outputs.fika_server_version }}
      fika_plugin_version: ${{ steps.clone-fika-server-and-plugin.outputs.fika_plugin_version }}
      fika_server_commit: ${{ steps.commit-hash.outputs.fika_server_commit }}
      fika_plugin_commit: ${{ steps.commit-hash.outputs.fika_plugin_commit }}
    steps:
      - name: Clone Fika Server And Plugin
        id: clone-fika-server-and-plugin
        shell: bash
        run: |
          serverPath="/workspace/build/fika/server"
          pluginPath="/workspace/build/fika/plugin"

          # Delete old remnants of the last build.
          if [ -d "$serverPath" ]; then
              rm -rf "$serverPath"
          fi
          sudo mkdir -p $serverPath

          if [ -d "$pluginPath" ]; then
              rm -rf "$pluginPath"
          fi
          sudo mkdir -p $pluginPath

          sudo chown -R `whoami`:`groups | awk '{print $1}'` $serverPath $pluginPath

          TARGET="${{ needs.prepare.outputs.tag_fika }}"

          echo "Cloning target: $TARGET"
          git clone ${{ needs.prepare.outputs.repo_fika_server }} --branch "$TARGET" --depth 1 "$serverPath"
          git clone ${{ needs.prepare.outputs.repo_fika_plugin }} --branch "$TARGET" --depth 1 "$pluginPath"

          echo "fika_server_version=${{ needs.prepare.outputs.tag_fika }}" >> "$GITHUB_OUTPUT"
          echo "fika_plugin_version=${{ needs.prepare.outputs.tag_fika }}" >> "$GITHUB_OUTPUT"

      - name: Output Commit Hash
        id: commit-hash
        shell: bash
        run: |
          echo "fika_server_commit=$(git -C ./server rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "fika_plugin_commit=$(git -C ./plugin rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
        working-directory: /workspace/build/fika

      - name: Set up .NET For Fika Server
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: '/workspace/build/fika/server/FikaServer/packages.lock.json'

      - name: Restore Fika Server
        run: |
          cd /workspace/build/fika/server
          dotnet restore FikaServer.slnx
          
      - name: Build Fika Server
        shell: bash
        run: |
          dotnet publish FikaServer/FikaServer.csproj --configuration Release --no-restore --output output/
          target_path='target/SPT/user/mods/fika-server'
          mkdir -p ${target_path}
          cp output/FikaServer.dll ${target_path}/
          cp output/FikaShared.dll ${target_path}/
          cp -r FikaServer/Assets ${target_path}/assets
          cp Licenses/* ${target_path}/
        working-directory: /workspace/build/fika/server

      - name: Upload Fika Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fika-server-artifact
          path: /workspace/build/fika/server/target
          retention-days: 1
          if-no-files-found: error

      - name: Set up .NET For Fika Plugin
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: '/workspace/build/fika/plugin/Fika.Core/packages.lock.json'

      - name: Restore Fika Plugin
        run: |
          cd /workspace/build/fika/plugin
          dotnet restore Fika-Plugin.slnx
  
      - name: Build Fika Plugin
        shell: bash
        run: |
          dotnet build Fika.Core/Fika.Core.csproj \
            --configuration Release \
            --no-restore \
            --output output/ \
            -p:Version=${{ needs.build-fika.outputs.fika_plugin_version }} \
            -p:AssemblyVersion=${{ needs.build-fika.outputs.fika_plugin_version }} \
            -p:InformationalVersion=${{ needs.build-fika.outputs.fika_plugin_version }}
          
          target_path='target/BepInEx/plugins/Fika'
          mkdir -p ${target_path}
          cp output/Fika.Core.dll ${target_path}/
          cp Licenses/* ${target_path}/
        working-directory: /workspace/build/fika/plugin

      - name: Upload Fika Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fika-plugin-artifact
          path: /workspace/build/fika/plugin/target
          retention-days: 1
          if-no-files-found: error
    
  build-docker-image:
    needs: [build-spt, build-fika]
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.compress_artifact.outputs.artifact_name }}
    permissions:
      contents: read
      packages: write  # make sure can write
    steps:
      - name: Clear Directory
        shell: bash
        run: |
          rm -rf ${{ github.workspace }}/release build
          mkdir -p ${{ github.workspace }}/release

      - name: Download SPT Server Artifact
        uses: actions/download-artifact@v4
        with:
          name: spt-server-artifact
          path: ${{ github.workspace }}/release/SPT

      - name: Download Fika Server Artifact
        uses: actions/download-artifact@v4
        with:
          name: fika-server-artifact
          path: ${{ github.workspace }}/release/SPT

      - name: Download Fika Plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: fika-plugin-artifact
          path: ${{ github.workspace }}/release/SPT

      - name: Check artifacts isExist
        id: check_artifact
        shell: bash
        run: |
          if [ ! -d "${{ github.workspace }}/release/SPT" ] || [ ! -d "${{ github.workspace }}/release/SPT/user" ]; then
            echo "Error: Artifact not found."
            exit 1
          fi
          ls -alhF ${{ github.workspace }}/release/SPT

      - name: Build Docker image
        run: |
          cd ${{ github.workspace }}/release

          # create fika-start script
          cat <<EOF > fika-start
          #!/bin/sh
          mkdir -p /fika/logs
          cd /fika
          /fika/SPT.Server.Linux | ts "%Y-%m-%d %H:%M:%S" | tee -a /fika/logs/fika.log
          EOF
          chmod +x ./SPT/SPT.Server.Linux fika-start

          # create Dockerfile
          cat <<EOF > Dockerfile
          FROM mcr.microsoft.com/dotnet/aspnet:9.0
          RUN apt update && apt install -y moreutils
          COPY ./SPT /fika
          COPY fika-start /bin/fika-start
          CMD ["/bin/fika-start"]
          EOF

          cat Dockerfile  # print Dockerfile content to check

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}/release
          file: ${{ github.workspace }}/release/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/spt-with-fika:latest
            ghcr.io/${{ github.repository_owner }}/spt-with-fika:${{ needs.build-spt.outputs.spt_server_version }}
            ghcr.io/${{ github.repository_owner }}/fika-debian12:latest
            ghcr.io/${{ github.repository_owner }}/fika-debian12:${{ needs.build-spt.outputs.spt_server_version }}

      - name: Compress Build Artifact
        id: compress_artifact
        run: |
          artifact_name=spt-${{ needs.build-spt.outputs.spt_server_version }}-fika-${{ needs.build-fika.outputs.fika_server_version }}.tgz
          tar -czvf ${{ github.workspace }}/release/$artifact_name ./SPT

          echo "artifact_name=$artifact_name" >> "$GITHUB_OUTPUT"
      
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_RELEASE }}
        with:
          tag_name: ${{ github.ref_name }}  # use trigger tag name
          release_name: ${{ needs.build-spt.outputs.spt_server_version }}
          draft: false
          prerelease: false

      - name: Upload Dockerfile to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_RELEASE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # get upload url from step `create_release`
          asset_path: ${{ github.workspace }}/release/Dockerfile  # upload Dockerfile as attachment
          asset_name: Dockerfile
          asset_content_type: application/octet-stream

      - name: Upload Build Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_RELEASE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # get upload url from step `create_release`
          asset_path: ${{ github.workspace }}/release/${{ steps.compress_artifact.outputs.artifact_name }}  # upload artifact
          asset_name: ${{ steps.compress_artifact.outputs.artifact_name }}
          asset_content_type: application/gzip

